package com.mycompany.di_p3_maven;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    
    
    
    public Menu() {
        
        FondoPanel panelFondo = new FondoPanel(); 
        this.setContentPane(panelFondo);
        
        //initComponents();
        componentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                        
    private void componentes() {
        java.awt.GridBagConstraints gridBagConstraints;
        
        java.awt.Container contentPane = this.getContentPane();

        jLtitulo = new javax.swing.JLabel();
        jBrutina = new javax.swing.JButton();
        jBcontrolpeso = new javax.swing.JButton();
        jLmenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        contentPane.setLayout(new java.awt.GridBagLayout());

        jLtitulo.setFont(new java.awt.Font("Segoe UI", 0, 36));
        jLtitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLtitulo.setText("MENU");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        contentPane.add(jLtitulo, gridBagConstraints);

        jBrutina.setFont(new java.awt.Font("Segoe UI", 0, 24));
        jBrutina.setText("Rutina Gimnasio");
        jBrutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrutinaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        
        contentPane.add(jBrutina, gridBagConstraints);

        jBcontrolpeso.setFont(new java.awt.Font("Segoe UI", 0, 24));
        jBcontrolpeso.setText("Control Peso");
        jBcontrolpeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcontrolpesoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        contentPane.add(jBcontrolpeso, gridBagConstraints);

        jLmenu.setFont(new java.awt.Font("Segoe UI", 0, 48));
        jLmenu.setText("DEPORTE Y SALUD");
        jLmenu.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;

        contentPane.add(jLmenu, gridBagConstraints);

        pack();
    }
    
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLtitulo = new javax.swing.JLabel();
        jBrutina = new javax.swing.JButton();
        jBcontrolpeso = new javax.swing.JButton();
        jLmenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLtitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLtitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLtitulo.setText("MENU");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLtitulo, gridBagConstraints);

        jBrutina.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBrutina.setText("Rutina Gimnasio");
        jBrutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrutinaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(jBrutina, gridBagConstraints);

        jBcontrolpeso.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBcontrolpeso.setText("Control Peso");
        jBcontrolpeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcontrolpesoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(jBcontrolpeso, gridBagConstraints);

        jLmenu.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLmenu.setText("DEPORTE Y SALUD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLmenu, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBrutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrutinaActionPerformed
        RutinaGym rg = new RutinaGym();
        rg.setVisible(true);
        System.out.println("Ventana abierta sin problema");
    }//GEN-LAST:event_jBrutinaActionPerformed

    private void jBcontrolpesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcontrolpesoActionPerformed
        Control c = new Control();
        c.setVisible(true);
    }//GEN-LAST:event_jBcontrolpesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcontrolpeso;
    private javax.swing.JButton jBrutina;
    private javax.swing.JLabel jLmenu;
    private javax.swing.JLabel jLtitulo;
    // End of variables declaration//GEN-END:variables
}
