import java.awt.List;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import java.awt.Container;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class RutinaGym extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RutinaGym.class.getName());

    private DefaultListModel<String> listModel; 

    
    /**
     * Creates new form RutinaGym
     */
    public RutinaGym() {
        
        //jPanelFondo = new FondoURL();
        
        Components();
        //initComponents();
        
        listModel = new DefaultListModel<>();
        
        jLejercicios.setModel(listModel);
    }
                         
    @SuppressWarnings("unchecked")                     
    private void Components() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLtitulo = new javax.swing.JLabel();
        jCBrutina = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLejercicios = new javax.swing.JList<>();
        
        jPanel = new FondoURL();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLtitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLtitulo.setText("Rutina de gimnasio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLtitulo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;

        jCBrutina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una rutina", "Pecho-Hombro-Triceps", "Espalda-Biceps", "Pierna" }));
        jCBrutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBrutinaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jCBrutina, gridBagConstraints);

        jLejercicios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Selecciona una rutina" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jLejercicios);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(jScrollPane1, gridBagConstraints);
        
        // AÑADE EL PANEL CON LA IMAGEN (jPanel, que ahora es FondoURL)
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        getContentPane().add(jPanel, gridBagConstraints);

        pack();
    }// </editor-fold>
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLtitulo = new javax.swing.JLabel();
        jCBrutina = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLejercicios = new javax.swing.JList<>();
        jPanel = new javax.swing.JPanel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLtitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLtitulo.setText("Rutina de gimnasio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLtitulo, gridBagConstraints);

        jCBrutina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una rutina", "Pecho-Hombro-Triceps", "Espalda-Biceps", "Pierna" }));
        jCBrutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBrutinaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jCBrutina, gridBagConstraints);

        jLejercicios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Selecciona una rutina" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jLejercicios);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(jScrollPane1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        getContentPane().add(jPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBrutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBrutinaActionPerformed
        Object item = jCBrutina.getSelectedItem();
        String caso = (String) item;
        listModel.clear();
        
        System.out.println(caso);
        
        
        switch (caso){
            case "Pecho-Hombro-Triceps":{
                String[] cadena = {"Press plano", "Press inclinado", "Peck Deck", "Averturas en Peck Deck", "Elevaciones laterales", "Extension de triceps", "Extension tras nuca"};
                for (String i: cadena){
                    listModel.addElement(i);
                }   
                break;
            }
            case "Espalda-Biceps":{
                String[] cadena = {"Jalon al pecho", "Remo", "Pull over", "Curl predicador", "Curl con codo detras del hombro"};
                for (String i: cadena){
                    listModel.addElement(i);
                }   
                break;
            }
            case "Pierna":{
                String[] cadena = {"Aduptor", "Sentadilla", "Extension de cuadriceps", "Prensa polea", "Isquios", "Aductor", "Soleo"};
                for (String i: cadena){
                    listModel.addElement(i);
                }   
                break;
            }
        }
    }//GEN-LAST:event_jCBrutinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> new RutinaGym().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBrutina;
    private javax.swing.JList<String> jLejercicios;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
